org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_id=structureexpansion
mod_version=26.3.0.1
maven_group=com.sunekaer.mods

curseforge_id=398430
modrinth_id=IKJL3zrR

# Dependencies
minecraft_version=26.3
minecraft_version_range=[26.3,27.0)

neoforge_version=26.3.0.6-beta
neoforge_version_range=[26.3,27.0)
