org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_id=structureexpansion
mod_version=99.0.0
maven_group=com.sunekaer.mods

curseforge_id=398430
modrinth_id=IKJL3zrR

# Dependencies
minecraft_version=26.1
minecraft_version_range=[26.1,26.2)

neoforge_version=26.1.0.8-beta
neoforge_version_range=[26.1,27.0)
