org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_id=structureexpansion
mod_version=102.0.0
maven_group=com.sunekaer.mods

curseforge_id=398430
modrinth_id=IKJL3zrR

# Dependencies
minecraft_version=26.2
minecraft_version_range=[26.2,26.3)

neoforge_version=26.2.0.6-beta
neoforge_version_range=[26.2,27.0)
