modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/nanite/Structure-Expansion/issues"
license="MIT License"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="Structure Expansion"
displayURL="https://www.curseforge.com/minecraft/mc-mods/structure-expansion"
iconFile="logo.png"
authors="Sunekaer, LatvianModder"
description='''
Small mod that Increases the size limit of the vanilla structure blocks

Increases the size limit of the structure block from 48x48x48 to 127x127x127
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="structureexpansion-common.mixins.json"
