name: Build & Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: nanite/workflows/.github/workflows/standard-release.yml@v1
    secrets:
      nanite-token: ${{ secrets.NANITE_DEPLOY }}
      curse-token: ${{ secrets.CURSE_DEPLOY }}